server:
  port: 0

spring:
  application:
    name: footballresource
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
          - football
          - football-ui
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/