management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,env,metrics,beans,loggers,football,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 0.01
football:
  folder: teams
spring:
  application:
    name: trading-service
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: packt
    password: packt
    hikari:
      connection-timeout: 5000
      max-lifetime: 10000
      validation-timeout: 2000