spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  profiles:
    active: default
logging:
  level:
    org.springframework.cloud.gateway: DEBUG