server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: "user"
      password: "password"
    oauth2:
      client:
        registration:
          football-gmail:
            client-id: "1072088765055-6e2h0c0ktgou0bnulamn6ocfjd0p6pl8.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          football-gmail:
            issuer-uri: https://accounts.google.com
            user-name-attribute: given_name
      authorizationserver:
        client:
          football:
            registration:
              client-id: "football"
              client-secret: "{noop}SuperSecret"
              client-authentication-methods:
                - "client_secret_post"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "football:read"
                - "football:admin"
          football-ui:
            registration:
              client-id: "football-ui"
              client-secret: "{noop}TheSecretSauce"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:9080/login/oauth2/code/football-ui"
              scopes:
                - "openid"
                - "profile"
                - "football:read"
                - "football:admin"
            require-authorization-consent: true
